### ISSUE TITLE
How to only read the "z" of ".laz" file ？

### ISSUE THREAD

**Issue by Lachiven** [LAStools/LAStools#114]
I use decompress_selective but the read time has no chage at all. Then I try to use the layer func of lastools, but dont konw how to put the attributes I want to the right layer. @rapidlasso

**Comment by kannes** [comment]
You got to provide some more information. What exactly do you mean by "only read the 'z'"? What exactly does your code or commandline invocations look like?

**Comment by esilvia** [comment]
The lastools/laszip library functions and indeed the LAS format itself are written such that each point's data is included as discrete packets with every attribute, rather than storing each attribute for all points.

That is, you can't read a point's Z value without also reading its X, Y, Intensity, etc values. As you've observed, there would be no performance advantage to doing so because of the way that the LAS file itself is structured. See the current version of the specification for more information: https://www.asprs.org/divisions-committees/lidar-division/laser-las-file-format-exchange-activities

LAZ is simply a compressed version of LAS, so it follows many of the same rules.

This is in contrast to some other formats such as a database that might store all points' X values, then all points' Y values, then all points' Z values, etc.

**Comment by rapidlasso** [comment]
Thanks Evon for that detailed explanation.
