### ISSUE TITLE
Defintion of minimum compiler

### ISSUE THREAD

**Issue by SunBlack** [LAStools/LAStools#19]
Currently there is Definition which is your minimum compiler requirement to compile this project or which compiler are supported. Because I currently have a lot of trouble with compiling this project I would help you a bit to modernize a few things so it is compiling with even with modern compiler. But for this I need information which compiler should be all supported.

The only thing I know is that you are still using Visual Studio 6. But which minimum version of e.g., gcc you are supporting? Or doesn't this matter as long VS6 is working? In this case I would define C++98 as used language and compile it with clang & gcc to test if all is still compiling.

**Comment by rapidlasso** [comment]
Thank for trying to help. The LASlib libraries' main purpose is to be our core engine in LAStools. It is only open source because why not. I try to address suggestions but only at the speed that I have and time does not permit anything for the next few weeks. That said, testing your changes against MSVC 6.0 is GREAT. But we have another 30 closed-source tools that statically link the library (it's our code so we are allowed to) that also need to be updated ...
