### ISSUE TITLE
File path errors -- not finding the specified path

### ISSUE THREAD

**Issue by swgeoscience** [LAStools/LAStools#200]
Hi,

Not sure what I'm doing wrong here, and perhaps a really obvious thing to fix, but, I am not getting any results generated when trying to create a dem from laz file.

I get the following message when running the tool - I can see I have juxtaposition of slashes but not sure if this is the issue. Having played around with the slashes, I've always generated the same output message.

Any help appreciated.

```
Algorithm 'las2dem (file)' starting…
Input parameters:
{ 'ADDITIONAL_OPTIONS' : '', 'ATTRIBUTE' : 0, 'CPU64' : False, 'FILTER_RETURN_CLASS_FLAGS1' : 0, 'GUI' : False, 'INPUT_LASLAZ' : 'C:\\tmp\\osgb_uav_lidar.copc.laz', 'OUTPUT_RASTER' : 'C:/tmp/test_dem.tif', 'PRODUCT' : 0, 'STEP' : 1, 'USE_TILE_BB' : False, 'VERBOSE' : True }

LAStools command line
C:\LAStools\bin\las2dem -i "C:\tmp\osgb_uav_lidar.copc.laz" -step 1.0 -v -o "C:/tmp/test_dem.tif"
LAStools console output
The system cannot find the path specified. 

Execution completed in 0.08 seconds
Results:
{'commands': ['C:\\LAStools\\bin\\las2dem',
'-i',
'"C:\\tmp\\osgb_uav_lidar.copc.laz"',
'-step',
'1.0',
'-v',
'-o',
'"C:/tmp/test_dem.tif"']}

Loading resulting layers
Algorithm 'las2dem (file)' finished
```

**Comment by rapidlasso** [comment]
This is a closed-source issue: Please post questions like this to the [support google group](https://groups.google.com/g/lastools) instead of the open source git repo.

- please use the 64 bit versions of LAStools
- use "\" instead of "/" as separator for your output file path
your command could look like
C:\LAStools\bin\las2dem64 -i "C:\tmp\osgb_uav_lidar.copc.laz" -step 1.0 -v -o "C:\tmp\test_dem.tif"
