### ISSUE TITLE
laszip_api.h include with wrong directory

### ISSUE THREAD

**Issue by plitkey** [LAStools/LAStools#35]
I downloaded the lastools-master and the laszip_api.c and laszip_api.h are both in LASzip/dll folder

Cannot open include file: 'laszip/laszip_api.h': No such file or directory

**Comment by rapidlasso** [comment]
Yeah ... the hobu team uses this more special include path <
laszip/laszip_api.h> whereas I just use "laszip_api.h". I have to manually
fix it in my end each time. Who can help?

On Aug 30, 2017 4:21 AM, "plitkey" <notifications@github.com> wrote:

I downloaded the lastools-master and the laszip_api.c and laszip_api.h are
both in LASzip/dll folder

Cannot open include file: 'laszip/laszip_api.h': No such file or directory

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LAStools/LAStools/issues/35>, or mute the thread

**Comment by rapidlasso** [comment]
Closed. This was a user error as @plitkey was trying to use both, the LASlib interface to LASzip and the laszip_dll.cpp / laszip_api.h interface in the same compile.
