### ISSUE TITLE
las2las -target_elevation_meter does not work as expected

### ISSUE THREAD

**Issue by Eskapp** [LAStools/LAStools#82]
Study case:
Input: A .laz file with elevation in feet.
My goal: Transforming the elevation to meters.

What I do:

I use the following command: `las2las -i <my_original_file> -o <my_output_file> -elevation_feet -target_elevation_meter` which from the documentation I understand as meaning: "I know that the elevation of the input file is in feet and I want it to be in meters". However, the output file has the exact same `z` values as the initial file. This might be a bug, in any case it would at least deserve a warning to the user when the elevation values remain unchanged

It seems to me that a workaround is to use `-scale_z 0.3048`.

The file I testes with is located at: [ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/NED/LPC/Projects/FL_CharlotteCounty_2007/laz/](url)
and named FL_CharlotteCounty_2007_000006.laz

**Comment by rapidlasso** [comment]
True. The switches such as '-elevation_feet' and '-target_elevation_meter' only kick either when missing CRS information is set in the LAS header (or exiting one is overridden) or when the data is (re-)projected but are ignored otherwise. Hence some '-target_utm 11north' or so needs to be in the command line as well. If you just want to fix a wrong scale then '-scale_z 0.3048' is the correct way of doing so. But I agree that a WARNING should be emitted.
